name: Publish vanity pages

permissions:
  contents: write      # cho phép push vào repo
  pages: write         # (không hại nếu dư)
  id-token: write

on:
  push:
    paths:
      - vanity.json      # rebuild khi manifest thay đổi
      - '**/*.go'          # hoặc khi code generator thay đổi
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Generate pages
        run: go run . build --config vanity.json --out public

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          publish_branch: gh-pages
